## Multi Input - somewhat reinforcement learning

3 inputs
1. all train input samples in one array
2. all train output samples in one array
2. the test input
3. the past predictions for this task

2 output
1. single pixel - value 0-9
2. the predicted size of the task


SUDO CODE TRAINING: 

1. get perfect samples for every pixel
2. predict every sample pixel 100.000x (e-greedy: first random then with model)
3. get discounted rewards for every prediction - (1 point for completed column, 1 point for completed row, 1 point for right pixel value)
4. train network on all collected samples
5. iterate over 2-4 until convergence ;)

In [90]:
#base
import os
import numpy as np
import pandas as pd

#tensorflow
from tensorflow.keras.layers import Input, Dense, Flatten, Conv1D, MaxPooling1D, concatenate, Subtract
from tensorflow.keras.models import Model

from tensorflow.keras.optimizers import Adam

import numpy as np
np.random.seed(0)  # Set a random seed for reproducibility

# utils
import utils.file_handling as io
from utils import plotting as plt


In [97]:
# MULTI-Input-Output-CNN

def create_model():
    input_1 = Input(shape=(None, 1), dtype='float32', name='input_1')
    input_2 = Input(shape=(None, 1), dtype='float32', name='input_2')
    input_3 = Input(shape=(None, 1), dtype='float32', name='input_3')
    input_4 = Input(shape=(32*32, 1), dtype='float32', name='input_4')

    x_1 = Conv1D(32, kernel_size=(4))(input_1)
    x_2 = Conv1D(32, kernel_size=(4))(input_2)
    x_sub = Subtract()([x_1, x_2])
    x_fin = Conv1D(32, kernel_size=(4))(x_sub)
    
    y_1 = Conv1D(32, kernel_size=(4))(input_3)
    y_1_pooling = MaxPooling1D(4)(y_1)
    y_1_flatten = Flatten()(y_1_pooling)
    y_2 = Conv1D(32, kernel_size=(4))(input_4)
    y_2_pooling = MaxPooling1D(4)(y_2)
    y_2_flatten = Flatten()(y_2_pooling)
    y_con = concatenate([y_1_flatten, y_2_flatten])
    y_fin = Conv1D(32, kernel_size=(4), name='test_picture_final_layer')(y_con)
    
    merge = concatenate([x_fin, y_fin])
    flat_layer = Flatten()(merge)

    
    out_1 = Dense(11, activation='relu')(flat_layer)
    out_1 = Dense(128, activation='relu')(out_1)
    out_1 = Dense(256, activation='relu')(out_1)
    out_1 = Dense(512, activation='relu')(out_1)
    out_1 = Dense(11, activation='softmax', name='pixel_predictor')(out_1)

    out_2 = Dense(64, activation='relu')(flat_layer)
    out_2 = Dense(2, activation='linear', name='shape_predictor')(out_2)
    
    model = Model(inputs=[input_1, input_2, input_3, input_4], outputs=[out_1, out_2])
    
    opt = Adam(lr=1e-3, decay=1e-3 / 200)
    losses = {
        "pixel_predictor": "categorical_crossentropy",
        "shape_predictor": "mean_absolute_error",
    }

    model.compile(loss=losses, optimizer=opt)
    return model

multi_cnn = create_model()

ValueError: Input 0 of layer test_picture_final_layer is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [None, None]

In [87]:
input_list_3[0]

array([7., 0., 7., 7., 0., 7., 7., 7., 0.])

In [92]:
multi_cnn.summary()

Model: "model_8"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            [(None, None, 1)]    0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            [(None, 1024, 1)]    0                                            
__________________________________________________________________________________________________
input_1 (InputLayer)            [(None, None, 1)]    0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, None, 1)]    0                                            
____________________________________________________________________________________________

In [76]:
training_path = os.getcwd()+'/data/training/'
train_data = io.get_tasks(training_path)

def preprocess_task(task):
    input_1 = [] # all training inputs flattened and concatenated
    input_2 = [] # all training outputs flattened and concatenated
    input_3 = [] # all test inputs 
    input_4 = np.array([10 for i in range(32*32)])# Initially None, will be filled with predicted values over time
    for sample in task['train']:
        input_1 = np.append(input_1, sample['input'])
        input_2 = np.append(input_2, sample['output'])
    for sample in task['test']:
        input_3 = np.append(input_3, sample['input'])
    return input_1, input_2, input_3, input_4

input_list_1, input_list_2, input_list_3, input_list_4 = [], [], [], []
for task in train_data:
    input_1, input_2, input_3, input_4 = preprocess_task(task)
    input_list_1.append(input_1)
    input_list_2.append(input_2)
    input_list_3.append(input_3)
    input_list_4.append(input_4)
input_list_3[0]

array([7., 0., 7., 7., 0., 7., 7., 7., 0.])

In [8]:
output_shape = []
for task in train_data:
    rows = len(task['test'][0]['output'])
    cols = len(task['test'][0]['output'][0])
    output_shape.append(np.array([rows, cols]))
output_shape = np.array(output_shape)
iterations_per_task = [np.prod(task) for task in output_shape]
output_shape[0]

array([9, 9])

In [10]:
len(input_list_3)

389

In [71]:
output_pixel_all_iterations = []
for task in train_data:
    full_output = np.array(task['test'][0]['output']).flatten()
    all_iters_task = []
    for i in range(len(full_output)): # number of iterations = number of pixels in test ouput
        pixel = full_output[i]
        pixel_dummies = np.array([pixel == i for i in range(0, 11)])
        all_iters_task.append(pixel_dummies)
    output_pixel_all_iterations.append(all_iters_task)
output_pixel_all_iterations[0]

[array([False, False, False, False, False, False, False,  True, False,
        False, False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False]),
 array([False, False, False, False, False, False, False,  True, False,
        False, False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False]),
 array([False, False, False, False, False, False, False,  True, False,
        False, False]),
 array([ True, False, False, False, False, False, False, False, False,
        False, False]),
 array([False, False, False, False, False, False, False,  True, False,
        False, False]),
 array([False, False, False, False, False, False, False,  True, False,
        False, False]),
 array([ True, False, False, False, False, False, 

In [13]:
len(output_pixel_all_iterations)

389

In [77]:
for i in [input_list_1[0].reshape(1, len(input_list_1[0]), 1),
               input_list_2[0].reshape(1, len(input_list_2[0]), 1),
               input_list_3[0].reshape(1, len(input_list_3[0]), 1),
               input_list_4[0].reshape(1, len(input_list_4[0]), 1)]:
    print(i.shape)

(1, 45, 1)
(1, 405, 1)
(1, 9, 1)
(1, 1024, 1)


In [93]:
multi_cnn.fit([input_list_1[0].reshape(1, len(input_list_1[0]), 1),
               input_list_2[0].reshape(1, len(input_list_2[0]), 1),
               input_list_3[0].reshape(1, len(input_list_3[0]), 1),
               input_list_4[0].reshape(1, len(input_list_4[0]), 1)],
              [np.expand_dims(output_pixel_all_iterations[0][0], axis=0),
               np.expand_dims(output_shape[0], axis=0)])

Train on 1 samples
1/1 [==============================] - 0s 275ms/sample


ValueError: Dimension 1 in both shapes must be equal, but are 1 and 255. Shapes are [?,1] and [?,255]. for 'model_8/concatenate_22/concat' (op: 'ConcatV2') with input shapes: [?,1,32], [?,255,32], [] and with computed input tensors: input[2] = <2>.

In [58]:
np.expand_dims(output_pixel_all_iterations[0][0], axis=0).shape

(1, 11)

In [51]:
np.expand_dims(output_pixel_all_iterations[0][0], axis=0).shape

(1, 11)

In [17]:
[None for i in range(32*32)]

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,